# Hephaestus System Configuration
# Update the values below with your specific configuration

# Remote Repository Settings
remote:
  token: "update-with-your-github-token"      # Required: Your GitHub personal access token
  owner: "update-with-your-org"               # Required: Your GitHub organization or username
  repository: "update-with-your-repo"         # Required: Your repository name
  branch: "main"                             # Optional: Branch to analyze (default: main)

# Model Service Settings
model:
  provider: "openai"                         # Required: AI provider (e.g., openai, anthropic)
  api_key: "update-with-your-api-key"        # Required: Your API key for the model service
  model_version: "gpt-4"                     # Required: Model version to use

# Logging Settings
log:
  level: "info"                              # Optional: Log level (debug, info, warn, error)
  format: "json"                             # Optional: Log format (json, text)

# Repository Settings
repository:
  path: "update-with-your-path"              # Required: Path to your local repository
  max_files: 10000                          # Optional: Max files to process (default: 10000)
  max_file_size: 1048576                    # Optional: Max file size in bytes (default: 1MB)

# Operational Mode
mode: "suggest"                             # Optional: Mode (suggest, deploy) 