collector:
  log_paths:
    - "/var/log/application/*.log"
    - "./logs/*.log"
  polling_interval: "5s"
  buffer_size: 1000
  
analyzer:
  error_patterns:
    - pattern: "panic:"
      severity: "critical"
    - pattern: "ERROR:"
      severity: "high"
    - pattern: "WARN:"
      severity: "medium"
  max_stack_depth: 50
  context_lines: 10
  
generator:
  fix_strategies:
    - type: "null_check"
      priority: 1
    - type: "exception_handling"
      priority: 2
    - type: "resource_cleanup"
      priority: 3
  max_fix_attempts: 3
  timeout: "30s"
  ai_model:
    provider: "openai"  # or "anthropic", "google", etc.
    model: "gpt-4"      # specific model name
    api_key: "${HEPHAESTUS_AI_KEY}"
    temperature: 0.7
    max_tokens: 2000
    fix_mode: "suggest"  # "suggest" or "direct"
      
deployment:
  auto_deploy: false
  require_human_approval: true
  sandbox_timeout: "30s"
  rollback_enabled: true
  max_concurrent_deployments: 1
  
knowledge:
  storage_path: "./data/knowledge"
  learning_enabled: true
  max_entries: 10000
  cleanup_interval: "24h"
  retention_period: "90d" 