# Hephaestus Default Configuration

# Remote Repository Configuration
remote:
  auth_token: ""  # GitHub authentication token
  repository_owner: ""  # Repository owner/organization
  repository_name: ""  # Repository name
  target_branch: "main"  # Default branch to analyze

# Model Service Configuration
model:
  service_provider: "openai"  # AI model provider (e.g., openai, anthropic)
  service_api_key: ""  # API key for the model service
  model_version: "gpt-4"  # Model version to use

# Logging Configuration
log:
  level: "info"  # Log level (debug, info, warn, error)
  output_format: "json"  # Log output format (json, text)

# Repository Configuration
repository:
  repository_path: ""  # Local repository path
  file_limit: 10000  # Maximum number of files to process
  file_size_limit: 1048576  # Maximum file size in bytes (1MB)

# Operational Mode
mode: "suggest"  # Operation mode (suggest, deploy) 