// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/hephaestus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration Messages
type SystemConfiguration struct {
	state              protoimpl.MessageState         `protogen:"open.v1"`
	RemoteSettings     *RemoteRepositoryConfiguration `protobuf:"bytes,1,opt,name=remote_settings,json=remoteSettings,proto3" json:"remote_settings,omitempty"`
	ModelSettings      *ModelServiceConfiguration     `protobuf:"bytes,2,opt,name=model_settings,json=modelSettings,proto3" json:"model_settings,omitempty"`
	LoggingSettings    *LoggingConfiguration          `protobuf:"bytes,3,opt,name=logging_settings,json=loggingSettings,proto3" json:"logging_settings,omitempty"`
	OperationalMode    string                         `protobuf:"bytes,4,opt,name=operational_mode,json=operationalMode,proto3" json:"operational_mode,omitempty"`
	RepositorySettings *RepositoryConfiguration       `protobuf:"bytes,5,opt,name=repository_settings,json=repositorySettings,proto3" json:"repository_settings,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SystemConfiguration) Reset() {
	*x = SystemConfiguration{}
	mi := &file_proto_hephaestus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfiguration) ProtoMessage() {}

func (x *SystemConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfiguration.ProtoReflect.Descriptor instead.
func (*SystemConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{0}
}

func (x *SystemConfiguration) GetRemoteSettings() *RemoteRepositoryConfiguration {
	if x != nil {
		return x.RemoteSettings
	}
	return nil
}

func (x *SystemConfiguration) GetModelSettings() *ModelServiceConfiguration {
	if x != nil {
		return x.ModelSettings
	}
	return nil
}

func (x *SystemConfiguration) GetLoggingSettings() *LoggingConfiguration {
	if x != nil {
		return x.LoggingSettings
	}
	return nil
}

func (x *SystemConfiguration) GetOperationalMode() string {
	if x != nil {
		return x.OperationalMode
	}
	return ""
}

func (x *SystemConfiguration) GetRepositorySettings() *RepositoryConfiguration {
	if x != nil {
		return x.RepositorySettings
	}
	return nil
}

type RemoteRepositoryConfiguration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthToken       string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	RepositoryOwner string                 `protobuf:"bytes,2,opt,name=repository_owner,json=repositoryOwner,proto3" json:"repository_owner,omitempty"`
	RepositoryName  string                 `protobuf:"bytes,3,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	TargetBranch    string                 `protobuf:"bytes,4,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoteRepositoryConfiguration) Reset() {
	*x = RemoteRepositoryConfiguration{}
	mi := &file_proto_hephaestus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteRepositoryConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteRepositoryConfiguration) ProtoMessage() {}

func (x *RemoteRepositoryConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteRepositoryConfiguration.ProtoReflect.Descriptor instead.
func (*RemoteRepositoryConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteRepositoryConfiguration) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RemoteRepositoryConfiguration) GetRepositoryOwner() string {
	if x != nil {
		return x.RepositoryOwner
	}
	return ""
}

func (x *RemoteRepositoryConfiguration) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *RemoteRepositoryConfiguration) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

type ModelServiceConfiguration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceProvider string                 `protobuf:"bytes,1,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"`
	ServiceApiKey   string                 `protobuf:"bytes,2,opt,name=service_api_key,json=serviceApiKey,proto3" json:"service_api_key,omitempty"`
	ModelVersion    string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelServiceConfiguration) Reset() {
	*x = ModelServiceConfiguration{}
	mi := &file_proto_hephaestus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelServiceConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelServiceConfiguration) ProtoMessage() {}

func (x *ModelServiceConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelServiceConfiguration.ProtoReflect.Descriptor instead.
func (*ModelServiceConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{2}
}

func (x *ModelServiceConfiguration) GetServiceProvider() string {
	if x != nil {
		return x.ServiceProvider
	}
	return ""
}

func (x *ModelServiceConfiguration) GetServiceApiKey() string {
	if x != nil {
		return x.ServiceApiKey
	}
	return ""
}

func (x *ModelServiceConfiguration) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type LoggingConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogLevel      string                 `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,2,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingConfiguration) Reset() {
	*x = LoggingConfiguration{}
	mi := &file_proto_hephaestus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingConfiguration) ProtoMessage() {}

func (x *LoggingConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingConfiguration.ProtoReflect.Descriptor instead.
func (*LoggingConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{3}
}

func (x *LoggingConfiguration) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *LoggingConfiguration) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type RepositoryConfiguration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepositoryPath string                 `protobuf:"bytes,1,opt,name=repository_path,json=repositoryPath,proto3" json:"repository_path,omitempty"`
	FileLimit      int32                  `protobuf:"varint,2,opt,name=file_limit,json=fileLimit,proto3" json:"file_limit,omitempty"`
	FileSizeLimit  int64                  `protobuf:"varint,3,opt,name=file_size_limit,json=fileSizeLimit,proto3" json:"file_size_limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RepositoryConfiguration) Reset() {
	*x = RepositoryConfiguration{}
	mi := &file_proto_hephaestus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryConfiguration) ProtoMessage() {}

func (x *RepositoryConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryConfiguration.ProtoReflect.Descriptor instead.
func (*RepositoryConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{4}
}

func (x *RepositoryConfiguration) GetRepositoryPath() string {
	if x != nil {
		return x.RepositoryPath
	}
	return ""
}

func (x *RepositoryConfiguration) GetFileLimit() int32 {
	if x != nil {
		return x.FileLimit
	}
	return 0
}

func (x *RepositoryConfiguration) GetFileSizeLimit() int64 {
	if x != nil {
		return x.FileSizeLimit
	}
	return 0
}

// Node Management Messages
type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LogLevel      string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	LogOutput     string                 `protobuf:"bytes,3,opt,name=log_output,json=logOutput,proto3" json:"log_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_hephaestus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *RegisterNodeRequest) GetLogOutput() string {
	if x != nil {
		return x.LogOutput
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_hephaestus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NodeStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeIdentifier string                 `protobuf:"bytes,1,opt,name=node_identifier,json=nodeIdentifier,proto3" json:"node_identifier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_proto_hephaestus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{7}
}

func (x *NodeStatusRequest) GetNodeIdentifier() string {
	if x != nil {
		return x.NodeIdentifier
	}
	return ""
}

type NodeStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeIdentifier       string                 `protobuf:"bytes,1,opt,name=node_identifier,json=nodeIdentifier,proto3" json:"node_identifier,omitempty"`
	OperationalStatus    string                 `protobuf:"bytes,2,opt,name=operational_status,json=operationalStatus,proto3" json:"operational_status,omitempty"`
	CurrentConfiguration *SystemConfiguration   `protobuf:"bytes,3,opt,name=current_configuration,json=currentConfiguration,proto3" json:"current_configuration,omitempty"`
	StatusMessage        string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_proto_hephaestus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{8}
}

func (x *NodeStatusResponse) GetNodeIdentifier() string {
	if x != nil {
		return x.NodeIdentifier
	}
	return ""
}

func (x *NodeStatusResponse) GetOperationalStatus() string {
	if x != nil {
		return x.OperationalStatus
	}
	return ""
}

func (x *NodeStatusResponse) GetCurrentConfiguration() *SystemConfiguration {
	if x != nil {
		return x.CurrentConfiguration
	}
	return nil
}

func (x *NodeStatusResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type UpdateNodeConfigurationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeIdentifier   string                 `protobuf:"bytes,1,opt,name=node_identifier,json=nodeIdentifier,proto3" json:"node_identifier,omitempty"`
	NewConfiguration *SystemConfiguration   `protobuf:"bytes,2,opt,name=new_configuration,json=newConfiguration,proto3" json:"new_configuration,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateNodeConfigurationRequest) Reset() {
	*x = UpdateNodeConfigurationRequest{}
	mi := &file_proto_hephaestus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeConfigurationRequest) ProtoMessage() {}

func (x *UpdateNodeConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeConfigurationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNodeConfigurationRequest) GetNodeIdentifier() string {
	if x != nil {
		return x.NodeIdentifier
	}
	return ""
}

func (x *UpdateNodeConfigurationRequest) GetNewConfiguration() *SystemConfiguration {
	if x != nil {
		return x.NewConfiguration
	}
	return nil
}

type UpdateNodeConfigurationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeIdentifier string                 `protobuf:"bytes,1,opt,name=node_identifier,json=nodeIdentifier,proto3" json:"node_identifier,omitempty"`
	StatusMessage  string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateNodeConfigurationResponse) Reset() {
	*x = UpdateNodeConfigurationResponse{}
	mi := &file_proto_hephaestus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeConfigurationResponse) ProtoMessage() {}

func (x *UpdateNodeConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeConfigurationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNodeConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateNodeConfigurationResponse) GetNodeIdentifier() string {
	if x != nil {
		return x.NodeIdentifier
	}
	return ""
}

func (x *UpdateNodeConfigurationResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *UpdateNodeConfigurationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeIdentifier string                 `protobuf:"bytes,1,opt,name=node_identifier,json=nodeIdentifier,proto3" json:"node_identifier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_proto_hephaestus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteNodeRequest) GetNodeIdentifier() string {
	if x != nil {
		return x.NodeIdentifier
	}
	return ""
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusMessage string                 `protobuf:"bytes,1,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_proto_hephaestus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteNodeResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *DeleteNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Log Processing Messages
type LogEntryData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeIdentifier string                 `protobuf:"bytes,1,opt,name=node_identifier,json=nodeIdentifier,proto3" json:"node_identifier,omitempty"`
	LogLevel       string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	LogMessage     string                 `protobuf:"bytes,3,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	LogTimestamp   string                 `protobuf:"bytes,4,opt,name=log_timestamp,json=logTimestamp,proto3" json:"log_timestamp,omitempty"`
	LogMetadata    map[string]string      `protobuf:"bytes,5,rep,name=log_metadata,json=logMetadata,proto3" json:"log_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ErrorTrace     string                 `protobuf:"bytes,6,opt,name=error_trace,json=errorTrace,proto3" json:"error_trace,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogEntryData) Reset() {
	*x = LogEntryData{}
	mi := &file_proto_hephaestus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryData) ProtoMessage() {}

func (x *LogEntryData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryData.ProtoReflect.Descriptor instead.
func (*LogEntryData) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{13}
}

func (x *LogEntryData) GetNodeIdentifier() string {
	if x != nil {
		return x.NodeIdentifier
	}
	return ""
}

func (x *LogEntryData) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *LogEntryData) GetLogMessage() string {
	if x != nil {
		return x.LogMessage
	}
	return ""
}

func (x *LogEntryData) GetLogTimestamp() string {
	if x != nil {
		return x.LogTimestamp
	}
	return ""
}

func (x *LogEntryData) GetLogMetadata() map[string]string {
	if x != nil {
		return x.LogMetadata
	}
	return nil
}

func (x *LogEntryData) GetErrorTrace() string {
	if x != nil {
		return x.ErrorTrace
	}
	return ""
}

type ProcessLogEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogEntry      *LogEntryData          `protobuf:"bytes,1,opt,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessLogEntryRequest) Reset() {
	*x = ProcessLogEntryRequest{}
	mi := &file_proto_hephaestus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessLogEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessLogEntryRequest) ProtoMessage() {}

func (x *ProcessLogEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessLogEntryRequest.ProtoReflect.Descriptor instead.
func (*ProcessLogEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessLogEntryRequest) GetLogEntry() *LogEntryData {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

type ProcessLogEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessLogEntryResponse) Reset() {
	*x = ProcessLogEntryResponse{}
	mi := &file_proto_hephaestus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessLogEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessLogEntryResponse) ProtoMessage() {}

func (x *ProcessLogEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessLogEntryResponse.ProtoReflect.Descriptor instead.
func (*ProcessLogEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessLogEntryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessLogEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamLogEntriesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeIdentifier string                 `protobuf:"bytes,1,opt,name=node_identifier,json=nodeIdentifier,proto3" json:"node_identifier,omitempty"`
	LogLevelFilter string                 `protobuf:"bytes,2,opt,name=log_level_filter,json=logLevelFilter,proto3" json:"log_level_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamLogEntriesRequest) Reset() {
	*x = StreamLogEntriesRequest{}
	mi := &file_proto_hephaestus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogEntriesRequest) ProtoMessage() {}

func (x *StreamLogEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogEntriesRequest.ProtoReflect.Descriptor instead.
func (*StreamLogEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{16}
}

func (x *StreamLogEntriesRequest) GetNodeIdentifier() string {
	if x != nil {
		return x.NodeIdentifier
	}
	return ""
}

func (x *StreamLogEntriesRequest) GetLogLevelFilter() string {
	if x != nil {
		return x.LogLevelFilter
	}
	return ""
}

// Solution Management Messages
type GetSolutionProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LogEntry      *LogEntryData          `protobuf:"bytes,2,opt,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSolutionProposalRequest) Reset() {
	*x = GetSolutionProposalRequest{}
	mi := &file_proto_hephaestus_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSolutionProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSolutionProposalRequest) ProtoMessage() {}

func (x *GetSolutionProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSolutionProposalRequest.ProtoReflect.Descriptor instead.
func (*GetSolutionProposalRequest) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{17}
}

func (x *GetSolutionProposalRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetSolutionProposalRequest) GetLogEntry() *LogEntryData {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

type SolutionProposal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SolutionId      string                 `protobuf:"bytes,1,opt,name=solution_id,json=solutionId,proto3" json:"solution_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AssociatedLog   *LogEntryData          `protobuf:"bytes,3,opt,name=associated_log,json=associatedLog,proto3" json:"associated_log,omitempty"`
	ProposedChanges string                 `protobuf:"bytes,4,opt,name=proposed_changes,json=proposedChanges,proto3" json:"proposed_changes,omitempty"`
	GenerationTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=generation_time,json=generationTime,proto3" json:"generation_time,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,6,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SolutionProposal) Reset() {
	*x = SolutionProposal{}
	mi := &file_proto_hephaestus_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolutionProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolutionProposal) ProtoMessage() {}

func (x *SolutionProposal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolutionProposal.ProtoReflect.Descriptor instead.
func (*SolutionProposal) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{18}
}

func (x *SolutionProposal) GetSolutionId() string {
	if x != nil {
		return x.SolutionId
	}
	return ""
}

func (x *SolutionProposal) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SolutionProposal) GetAssociatedLog() *LogEntryData {
	if x != nil {
		return x.AssociatedLog
	}
	return nil
}

func (x *SolutionProposal) GetProposedChanges() string {
	if x != nil {
		return x.ProposedChanges
	}
	return ""
}

func (x *SolutionProposal) GetGenerationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.GenerationTime
	}
	return nil
}

func (x *SolutionProposal) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

type GetSolutionProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solution      *SolutionProposal      `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSolutionProposalResponse) Reset() {
	*x = GetSolutionProposalResponse{}
	mi := &file_proto_hephaestus_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSolutionProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSolutionProposalResponse) ProtoMessage() {}

func (x *GetSolutionProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSolutionProposalResponse.ProtoReflect.Descriptor instead.
func (*GetSolutionProposalResponse) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{19}
}

func (x *GetSolutionProposalResponse) GetSolution() *SolutionProposal {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *GetSolutionProposalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ValidateSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solution      *SolutionProposal      `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSolutionRequest) Reset() {
	*x = ValidateSolutionRequest{}
	mi := &file_proto_hephaestus_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSolutionRequest) ProtoMessage() {}

func (x *ValidateSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSolutionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSolutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{20}
}

func (x *ValidateSolutionRequest) GetSolution() *SolutionProposal {
	if x != nil {
		return x.Solution
	}
	return nil
}

type ValidateSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSolutionResponse) Reset() {
	*x = ValidateSolutionResponse{}
	mi := &file_proto_hephaestus_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSolutionResponse) ProtoMessage() {}

func (x *ValidateSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hephaestus_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSolutionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSolutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_hephaestus_proto_rawDescGZIP(), []int{21}
}

func (x *ValidateSolutionResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateSolutionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_hephaestus_proto protoreflect.FileDescriptor

const file_proto_hephaestus_proto_rawDesc = "" +
	"\n" +
	"\x16proto/hephaestus.proto\x12\n" +
	"hephaestus\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\x13SystemConfiguration\x12R\n" +
	"\x0fremote_settings\x18\x01 \x01(\v2).hephaestus.RemoteRepositoryConfigurationR\x0eremoteSettings\x12L\n" +
	"\x0emodel_settings\x18\x02 \x01(\v2%.hephaestus.ModelServiceConfigurationR\rmodelSettings\x12K\n" +
	"\x10logging_settings\x18\x03 \x01(\v2 .hephaestus.LoggingConfigurationR\x0floggingSettings\x12)\n" +
	"\x10operational_mode\x18\x04 \x01(\tR\x0foperationalMode\x12T\n" +
	"\x13repository_settings\x18\x05 \x01(\v2#.hephaestus.RepositoryConfigurationR\x12repositorySettings\"\xb7\x01\n" +
	"\x1dRemoteRepositoryConfiguration\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12)\n" +
	"\x10repository_owner\x18\x02 \x01(\tR\x0frepositoryOwner\x12'\n" +
	"\x0frepository_name\x18\x03 \x01(\tR\x0erepositoryName\x12#\n" +
	"\rtarget_branch\x18\x04 \x01(\tR\ftargetBranch\"\x93\x01\n" +
	"\x19ModelServiceConfiguration\x12)\n" +
	"\x10service_provider\x18\x01 \x01(\tR\x0fserviceProvider\x12&\n" +
	"\x0fservice_api_key\x18\x02 \x01(\tR\rserviceApiKey\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"X\n" +
	"\x14LoggingConfiguration\x12\x1b\n" +
	"\tlog_level\x18\x01 \x01(\tR\blogLevel\x12#\n" +
	"\routput_format\x18\x02 \x01(\tR\foutputFormat\"\x89\x01\n" +
	"\x17RepositoryConfiguration\x12'\n" +
	"\x0frepository_path\x18\x01 \x01(\tR\x0erepositoryPath\x12\x1d\n" +
	"\n" +
	"file_limit\x18\x02 \x01(\x05R\tfileLimit\x12&\n" +
	"\x0ffile_size_limit\x18\x03 \x01(\x03R\rfileSizeLimit\"j\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\x12\x1d\n" +
	"\n" +
	"log_output\x18\x03 \x01(\tR\tlogOutput\"D\n" +
	"\x14RegisterNodeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"<\n" +
	"\x11NodeStatusRequest\x12'\n" +
	"\x0fnode_identifier\x18\x01 \x01(\tR\x0enodeIdentifier\"\xe9\x01\n" +
	"\x12NodeStatusResponse\x12'\n" +
	"\x0fnode_identifier\x18\x01 \x01(\tR\x0enodeIdentifier\x12-\n" +
	"\x12operational_status\x18\x02 \x01(\tR\x11operationalStatus\x12T\n" +
	"\x15current_configuration\x18\x03 \x01(\v2\x1f.hephaestus.SystemConfigurationR\x14currentConfiguration\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\"\x97\x01\n" +
	"\x1eUpdateNodeConfigurationRequest\x12'\n" +
	"\x0fnode_identifier\x18\x01 \x01(\tR\x0enodeIdentifier\x12L\n" +
	"\x11new_configuration\x18\x02 \x01(\v2\x1f.hephaestus.SystemConfigurationR\x10newConfiguration\"\x8b\x01\n" +
	"\x1fUpdateNodeConfigurationResponse\x12'\n" +
	"\x0fnode_identifier\x18\x01 \x01(\tR\x0enodeIdentifier\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"<\n" +
	"\x11DeleteNodeRequest\x12'\n" +
	"\x0fnode_identifier\x18\x01 \x01(\tR\x0enodeIdentifier\"U\n" +
	"\x12DeleteNodeResponse\x12%\n" +
	"\x0estatus_message\x18\x01 \x01(\tR\rstatusMessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xc9\x02\n" +
	"\fLogEntryData\x12'\n" +
	"\x0fnode_identifier\x18\x01 \x01(\tR\x0enodeIdentifier\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\x12\x1f\n" +
	"\vlog_message\x18\x03 \x01(\tR\n" +
	"logMessage\x12#\n" +
	"\rlog_timestamp\x18\x04 \x01(\tR\flogTimestamp\x12L\n" +
	"\flog_metadata\x18\x05 \x03(\v2).hephaestus.LogEntryData.LogMetadataEntryR\vlogMetadata\x12\x1f\n" +
	"\verror_trace\x18\x06 \x01(\tR\n" +
	"errorTrace\x1a>\n" +
	"\x10LogMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x16ProcessLogEntryRequest\x125\n" +
	"\tlog_entry\x18\x01 \x01(\v2\x18.hephaestus.LogEntryDataR\blogEntry\"G\n" +
	"\x17ProcessLogEntryResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"l\n" +
	"\x17StreamLogEntriesRequest\x12'\n" +
	"\x0fnode_identifier\x18\x01 \x01(\tR\x0enodeIdentifier\x12(\n" +
	"\x10log_level_filter\x18\x02 \x01(\tR\x0elogLevelFilter\"l\n" +
	"\x1aGetSolutionProposalRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x125\n" +
	"\tlog_entry\x18\x02 \x01(\v2\x18.hephaestus.LogEntryDataR\blogEntry\"\xa8\x02\n" +
	"\x10SolutionProposal\x12\x1f\n" +
	"\vsolution_id\x18\x01 \x01(\tR\n" +
	"solutionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12?\n" +
	"\x0eassociated_log\x18\x03 \x01(\v2\x18.hephaestus.LogEntryDataR\rassociatedLog\x12)\n" +
	"\x10proposed_changes\x18\x04 \x01(\tR\x0fproposedChanges\x12C\n" +
	"\x0fgeneration_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0egenerationTime\x12)\n" +
	"\x10confidence_score\x18\x06 \x01(\x01R\x0fconfidenceScore\"m\n" +
	"\x1bGetSolutionProposalResponse\x128\n" +
	"\bsolution\x18\x01 \x01(\v2\x1c.hephaestus.SolutionProposalR\bsolution\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"S\n" +
	"\x17ValidateSolutionRequest\x128\n" +
	"\bsolution\x18\x01 \x01(\v2\x1c.hephaestus.SolutionProposalR\bsolution\"K\n" +
	"\x18ValidateSolutionResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xef\x05\n" +
	"\x11HephaestusService\x12Q\n" +
	"\fRegisterNode\x12\x1f.hephaestus.RegisterNodeRequest\x1a .hephaestus.RegisterNodeResponse\x12N\n" +
	"\rGetNodeStatus\x12\x1d.hephaestus.NodeStatusRequest\x1a\x1e.hephaestus.NodeStatusResponse\x12r\n" +
	"\x17UpdateNodeConfiguration\x12*.hephaestus.UpdateNodeConfigurationRequest\x1a+.hephaestus.UpdateNodeConfigurationResponse\x12K\n" +
	"\n" +
	"DeleteNode\x12\x1d.hephaestus.DeleteNodeRequest\x1a\x1e.hephaestus.DeleteNodeResponse\x12Z\n" +
	"\x0fProcessLogEntry\x12\".hephaestus.ProcessLogEntryRequest\x1a#.hephaestus.ProcessLogEntryResponse\x12S\n" +
	"\x10StreamLogEntries\x12#.hephaestus.StreamLogEntriesRequest\x1a\x18.hephaestus.LogEntryData0\x01\x12f\n" +
	"\x13GetSolutionProposal\x12&.hephaestus.GetSolutionProposalRequest\x1a'.hephaestus.GetSolutionProposalResponse\x12]\n" +
	"\x10ValidateSolution\x12#.hephaestus.ValidateSolutionRequest\x1a$.hephaestus.ValidateSolutionResponseB%Z#github.com/HoyeonS/hephaestus/protob\x06proto3"

var (
	file_proto_hephaestus_proto_rawDescOnce sync.Once
	file_proto_hephaestus_proto_rawDescData []byte
)

func file_proto_hephaestus_proto_rawDescGZIP() []byte {
	file_proto_hephaestus_proto_rawDescOnce.Do(func() {
		file_proto_hephaestus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hephaestus_proto_rawDesc), len(file_proto_hephaestus_proto_rawDesc)))
	})
	return file_proto_hephaestus_proto_rawDescData
}

var file_proto_hephaestus_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_hephaestus_proto_goTypes = []any{
	(*SystemConfiguration)(nil),             // 0: hephaestus.SystemConfiguration
	(*RemoteRepositoryConfiguration)(nil),   // 1: hephaestus.RemoteRepositoryConfiguration
	(*ModelServiceConfiguration)(nil),       // 2: hephaestus.ModelServiceConfiguration
	(*LoggingConfiguration)(nil),            // 3: hephaestus.LoggingConfiguration
	(*RepositoryConfiguration)(nil),         // 4: hephaestus.RepositoryConfiguration
	(*RegisterNodeRequest)(nil),             // 5: hephaestus.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),            // 6: hephaestus.RegisterNodeResponse
	(*NodeStatusRequest)(nil),               // 7: hephaestus.NodeStatusRequest
	(*NodeStatusResponse)(nil),              // 8: hephaestus.NodeStatusResponse
	(*UpdateNodeConfigurationRequest)(nil),  // 9: hephaestus.UpdateNodeConfigurationRequest
	(*UpdateNodeConfigurationResponse)(nil), // 10: hephaestus.UpdateNodeConfigurationResponse
	(*DeleteNodeRequest)(nil),               // 11: hephaestus.DeleteNodeRequest
	(*DeleteNodeResponse)(nil),              // 12: hephaestus.DeleteNodeResponse
	(*LogEntryData)(nil),                    // 13: hephaestus.LogEntryData
	(*ProcessLogEntryRequest)(nil),          // 14: hephaestus.ProcessLogEntryRequest
	(*ProcessLogEntryResponse)(nil),         // 15: hephaestus.ProcessLogEntryResponse
	(*StreamLogEntriesRequest)(nil),         // 16: hephaestus.StreamLogEntriesRequest
	(*GetSolutionProposalRequest)(nil),      // 17: hephaestus.GetSolutionProposalRequest
	(*SolutionProposal)(nil),                // 18: hephaestus.SolutionProposal
	(*GetSolutionProposalResponse)(nil),     // 19: hephaestus.GetSolutionProposalResponse
	(*ValidateSolutionRequest)(nil),         // 20: hephaestus.ValidateSolutionRequest
	(*ValidateSolutionResponse)(nil),        // 21: hephaestus.ValidateSolutionResponse
	nil,                                     // 22: hephaestus.LogEntryData.LogMetadataEntry
	(*timestamppb.Timestamp)(nil),           // 23: google.protobuf.Timestamp
}
var file_proto_hephaestus_proto_depIdxs = []int32{
	1,  // 0: hephaestus.SystemConfiguration.remote_settings:type_name -> hephaestus.RemoteRepositoryConfiguration
	2,  // 1: hephaestus.SystemConfiguration.model_settings:type_name -> hephaestus.ModelServiceConfiguration
	3,  // 2: hephaestus.SystemConfiguration.logging_settings:type_name -> hephaestus.LoggingConfiguration
	4,  // 3: hephaestus.SystemConfiguration.repository_settings:type_name -> hephaestus.RepositoryConfiguration
	0,  // 4: hephaestus.NodeStatusResponse.current_configuration:type_name -> hephaestus.SystemConfiguration
	0,  // 5: hephaestus.UpdateNodeConfigurationRequest.new_configuration:type_name -> hephaestus.SystemConfiguration
	22, // 6: hephaestus.LogEntryData.log_metadata:type_name -> hephaestus.LogEntryData.LogMetadataEntry
	13, // 7: hephaestus.ProcessLogEntryRequest.log_entry:type_name -> hephaestus.LogEntryData
	13, // 8: hephaestus.GetSolutionProposalRequest.log_entry:type_name -> hephaestus.LogEntryData
	13, // 9: hephaestus.SolutionProposal.associated_log:type_name -> hephaestus.LogEntryData
	23, // 10: hephaestus.SolutionProposal.generation_time:type_name -> google.protobuf.Timestamp
	18, // 11: hephaestus.GetSolutionProposalResponse.solution:type_name -> hephaestus.SolutionProposal
	18, // 12: hephaestus.ValidateSolutionRequest.solution:type_name -> hephaestus.SolutionProposal
	5,  // 13: hephaestus.HephaestusService.RegisterNode:input_type -> hephaestus.RegisterNodeRequest
	7,  // 14: hephaestus.HephaestusService.GetNodeStatus:input_type -> hephaestus.NodeStatusRequest
	9,  // 15: hephaestus.HephaestusService.UpdateNodeConfiguration:input_type -> hephaestus.UpdateNodeConfigurationRequest
	11, // 16: hephaestus.HephaestusService.DeleteNode:input_type -> hephaestus.DeleteNodeRequest
	14, // 17: hephaestus.HephaestusService.ProcessLogEntry:input_type -> hephaestus.ProcessLogEntryRequest
	16, // 18: hephaestus.HephaestusService.StreamLogEntries:input_type -> hephaestus.StreamLogEntriesRequest
	17, // 19: hephaestus.HephaestusService.GetSolutionProposal:input_type -> hephaestus.GetSolutionProposalRequest
	20, // 20: hephaestus.HephaestusService.ValidateSolution:input_type -> hephaestus.ValidateSolutionRequest
	6,  // 21: hephaestus.HephaestusService.RegisterNode:output_type -> hephaestus.RegisterNodeResponse
	8,  // 22: hephaestus.HephaestusService.GetNodeStatus:output_type -> hephaestus.NodeStatusResponse
	10, // 23: hephaestus.HephaestusService.UpdateNodeConfiguration:output_type -> hephaestus.UpdateNodeConfigurationResponse
	12, // 24: hephaestus.HephaestusService.DeleteNode:output_type -> hephaestus.DeleteNodeResponse
	15, // 25: hephaestus.HephaestusService.ProcessLogEntry:output_type -> hephaestus.ProcessLogEntryResponse
	13, // 26: hephaestus.HephaestusService.StreamLogEntries:output_type -> hephaestus.LogEntryData
	19, // 27: hephaestus.HephaestusService.GetSolutionProposal:output_type -> hephaestus.GetSolutionProposalResponse
	21, // 28: hephaestus.HephaestusService.ValidateSolution:output_type -> hephaestus.ValidateSolutionResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_hephaestus_proto_init() }
func file_proto_hephaestus_proto_init() {
	if File_proto_hephaestus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hephaestus_proto_rawDesc), len(file_proto_hephaestus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hephaestus_proto_goTypes,
		DependencyIndexes: file_proto_hephaestus_proto_depIdxs,
		MessageInfos:      file_proto_hephaestus_proto_msgTypes,
	}.Build()
	File_proto_hephaestus_proto = out.File
	file_proto_hephaestus_proto_goTypes = nil
	file_proto_hephaestus_proto_depIdxs = nil
}
